### ISSUE TITLE
Add gozip in my Project (Error Build) - is a program, not an importable package

### ISSUE THREAD

**Issue by jniltinho** [sanderhahn/gozip#1]
Error Build
import "github.com/sanderhahn/gozip" is a program, not an importable package

**Comment by sanderhahn** [comment]
Hello Jniltinho,

You can install the gozip executable using: `go get github.com/sanderhahn/gozip`, see the readme for some explanation. The program is not a library that you can import, but more an example of how the excellent archive/zip library in Go can be used (https://golang.org/pkg/archive/zip/).

Feel free to [reuse any code](https://github.com/sanderhahn/gozip/blob/master/gozip.go) as you see fit :-) Do you think i should make it into a library?

Best regards,
Sander Hahn

**Comment by jniltinho** [comment]
Hello @sanderhahn  
https://github.com/jniltinho/gozip
I will add other libs, download files using
github.com/nareix/curl
INI using
github.com/vaughan0/go-ini
Goquery using
github.com/PuerkitoBio/goquery

I am creating a binary to deploy automation for Linux, Mac, FreeBSD and Windows

Thanks!!!!

**Comment by sanderhahn** [comment]
Please note that patchzip was necessary in Go 1.4, because there was no SetOffset call on the zip Writer. This has been fixed in Go 1.5: https://github.com/golang/go/issues/8669
You can now remove the patchzip library from your project (see https://github.com/sanderhahn/gozip/commit/41063ef846d1c75fca9ab55dcf6dbcda45f78e0e).

Here is an article how to build a proper command line tool in Go:
https://medium.com/@voxxit/supercharge-your-devops-arsenal-part-i-417280563cd5

Good luck :)

**Comment by jniltinho** [comment]
:100:  :+1:
